const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEEzcWNRdENLYVhlaXdxWVRZcnRRREhxc3Z3T2tiblRmOUNoTU1GUFVYMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVW1Gam9lWTg4THNyUDZ5dmQ2VUd0TWZlOC82SGxqSDhJNXFRUDRITUpGdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtQ0hjYjVnRC90NXhrTlJoNHliN084WEF2UFE5ckF6a25haFZubHZHS21vPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrUGN2OVRmSDBENXI4L1VoR215aCs5d1ZzU2IydFJTWEY4UmVoMkVMNzJZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVKUEJjRWQzeXV2ZlEyZnM4amovN0JuZW44OU43SzFNYXRzcElJM0ZIVTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilp1MzJWc0RIRFExQ3N6cHFNUnF3QjFtVnlLVUh5VHZtNzRPejliWER2MVU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUw1TFdheFRBTHN5L3VuYnQ1MVFScUJLcVZGVTJvVVc1S0NMZkJIcGczZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZzNGNGJhN2tJekQ2c0lqL0M2azVDMW0zRUd0N3BLb1hobXk5NmFXZ1V5cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJrUEtiQXROd1lHWDl5cXRzcVYxY0VzWGtab2pIV0hYZHp5YUFIYXJUSTNsTEF3N0t0VVIyUVd2alhselpHMjI5OGZXa2RKbDdqT2tWU3c2cmlKM0RnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ1LCJhZHZTZWNyZXRLZXkiOiJyT0pGaG9sMGdHMkxtUEdzdEE1bXFpYmErUlFDVndybkkrMXNEQTI2TEVZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzI3MTI0MTY1OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1RUYwNjc1MTQzNzIzNkQ0QTcxRDJGQkQxNjQwOEFFNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1ODQ2NjMyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMyNzEyNDE2NThAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNUVEM0RGQkQyODY5RDkwN0E0QjFDQUYxRDRCQ0U2MzEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTg0NjYzNn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiYnJoSnd2WDhUUWVzY29sVGx2aVNhdyIsInBob25lSWQiOiIxYmM0NzIyZi1hZTlmLTQwNDUtOTY5MS0xYjYzNzQ3NDk1ODYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidnk0dzBvaGlLRlVMa012Y2JtM01RZUNQdEw4PSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZsNEFtenJRY1dCL3dpRVNaaUIwUk5Pbld5Yz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiIzMzhNMVk1SyIsIm1lIjp7ImlkIjoiOTIzMjcxMjQxNjU4OjQyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Iml0cyBBaG1hZCDwn5iYIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLek8vNlVGRU5YVjI3c0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiIveElwTkhMVkRqRXhWK3NETWp0V0xUYngzeE45UUpOZEh1bmMxeVBpL1QwPSIsImFjY291bnRTaWduYXR1cmUiOiIrSSs4azFZZXN1T0N0Wjh6RG5WYW9pWG5uMzVoTExacUlSYnorc1E2WkRWM3BVVWJzY3NyalpNYk1BUmdNVUtzMFN2QU0zcEtGa2c1VGU0T2hPejVBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoia01ycDNNYXhibTladzZpRit4Mm8vZVFuZjVEMVBhTDFiWXdmMDZ2eTdiV2JDeFdNalhWSEN1a0FMa21ORTJaZkFkV2dGU29JcXlNWXJrcE5PVGM3RGc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMyNzEyNDE2NTg6NDJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZjhTS1RSeTFRNHhNVmZyQXpJN1ZpMDI4ZDhUZlVDVFhSN3AzTmNqNHYwOSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTg0NjYyNiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFOVzAifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
